#!/usr/bin/env node
// Keeps the label vocabulary honest, and writes down what it resolves to.
//
// Three things, in order of how often they run:
//
//   (default)      Offline. Checks the moon graph against the tag vocabulary
//                  labels.yml declares, and that labels.lock.json is current.
//                  No API calls, no token, no network. This is what CI runs.
//   --write-lock   Regenerate labels.lock.json from labels.yml plus the graph.
//   --remote       Also compare against GitHub. Implied by --apply.
//   --apply        Create, rename, and retire labels on GitHub.
//
// The default used to reach GitHub on every run -- two calls, about 750ms --
// to answer a question CI was not asking. The check that matters is whether a
// moon.yml declares a tag the vocabulary does not, and that is answerable from
// files on disk. Talking to GitHub is now something you ask for.
//
// What is deliberately NOT cached is GitHub's own state. A committed snapshot
// of what labels exist would go stale the moment someone edits one in the web
// UI, and a cache that can be quietly wrong is worse than no cache in a system
// whose whole purpose is catching drift. labels.lock.json holds only what is
// derived from files in this repository, so it is reproducible rather than
// remembered.
//
// No dependencies: a hand-rolled reader for the small YAML subset labels.yml
// uses, and gh for the API.
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
export const LOCK = 'labels.lock.json'

// Only what labels.yml uses: `family:` at column 0, then `- name:` items whose
// scalars are quoted. A real parser would be a dependency, and this file is
// checked by CI against the graph, so a shape it cannot read fails loudly.
export function parseLabels(text) {
  const out = {}
  let family = null
  let item = null
  for (const raw of text.split('\n')) {
    const line = raw.replace(/\s+$/, '')
    if (!line || /^\s*#/.test(line)) continue
    const fam = line.match(/^([a-z][a-z0-9_]*):$/)
    if (fam) { family = fam[1]; out[family] = []; item = null; continue }
    if (!family) continue
    const start = line.match(/^\s*-\s*name:\s*'(.+)'$/)
    if (start) { item = { name: start[1] }; out[family].push(item); continue }
    const field = line.match(/^\s+([a-z]+):\s*(?:'(.*)'|"(.*)")$/)
    if (field && item) item[field[1]] = field[2] ?? field[3]
  }
  return out
}

// The labels a project's own metadata implies. Pure, so it can be tested
// without a graph.
export function routesFor(projects) {
  return projects
    .map((p) => ({
      source: p.source,
      labels: [`area/${p.source.split('/')[0]}`, ...(p.config?.tags ?? []).map((t) => `tag/${t}`)].sort(),
    }))
    .sort((a, b) => (a.source < b.source ? -1 : 1))
}

// Sorted, no timestamp: the file has to be reproducible, or "is the lock
// current" becomes a question about when it was written rather than what it
// says.
export function buildLock(families, projects) {
  const { retire = [], ...keep } = families
  const labels = Object.entries(keep)
    .flatMap(([family, ls]) => ls.map((l) => ({ ...l, family })))
    .sort((a, b) => (a.name < b.name ? -1 : 1))
  return {
    comment: `Generated by tools/labels/sync.mjs --write-lock. Do not edit.`,
    labels,
    retire: retire.map((l) => l.name).sort(),
    routes: routesFor(projects),
  }
}

const sh = (cmd, args) => execFileSync(cmd, args, { encoding: 'utf8', maxBuffer: 64 << 20 })
const norm = (c) => (c ?? '').replace(/^#/, '').toLowerCase()

function main() {
  const argv = process.argv.slice(2)
  const apply = argv.includes('--apply')
  const writeLock = argv.includes('--write-lock')
  const remote = apply || argv.includes('--remote')

  const families = parseLabels(readFileSync(join(HERE, 'labels.yml'), 'utf8'))
  const { retire: retiring = [], ...keep } = families
  const declared = Object.values(keep).flat()
  const declaredTags = new Set((families.tag ?? []).map((l) => l.name.slice('tag/'.length)))
  const declaredAreas = new Set((families.area ?? []).map((l) => l.name.slice('area/'.length)))

  const projects = JSON.parse(sh('moon', ['query', 'projects'])).projects
  const usedTags = new Set(projects.flatMap((p) => p.config?.tags ?? []))
  const usedAreas = new Set(projects.map((p) => p.source.split('/')[0]))

  const problems = []
  const notes = []

  for (const tag of [...usedTags].sort()) {
    if (!declaredTags.has(tag)) {
      const where = projects.filter((p) => (p.config?.tags ?? []).includes(tag)).map((p) => p.id)
      problems.push(`tag '${tag}' is used by ${where.join(', ')} but not declared in labels.yml`)
    }
  }
  for (const tag of [...declaredTags].sort()) {
    if (!usedTags.has(tag)) notes.push(`tag '${tag}' is declared but no project uses it`)
  }
  for (const area of [...usedAreas].sort()) {
    if (!declaredAreas.has(area)) problems.push(`projects live under '${area}/' but area/${area} is not declared`)
  }

  // The lock is derived, so a stale one is a mistake rather than a decision --
  // it means someone edited labels.yml or a moon.yml and did not regenerate.
  const lockPath = join(HERE, LOCK)
  const fresh = JSON.stringify(buildLock(families, projects), null, 2) + '\n'
  if (writeLock) {
    writeFileSync(lockPath, fresh)
    console.log(`wrote ${LOCK}`)
  } else {
    let current = null
    try { current = readFileSync(lockPath, 'utf8') } catch {}
    if (current === null) problems.push(`${LOCK} is missing -- run: node tools/labels/sync.mjs --write-lock`)
    else if (current !== fresh) problems.push(`${LOCK} is out of date -- run: node tools/labels/sync.mjs --write-lock`)
  }

  for (const p of problems) console.error(`error: ${p}`)
  for (const n of notes) console.warn(`warn:  ${n}`)

  if (!remote) {
    if (!problems.length) console.log(`${declared.length} declared, graph and ${LOCK} agree. GitHub not contacted.`)
    process.exit(problems.length ? 1 : 0)
  }

  // Labels are per-repository, and gh picks its target from the working
  // directory. Naming it out loud makes an --apply from the wrong clone
  // obvious before it changes anything.
  let existing = null
  try {
    console.log(`repository: ${sh('gh', ['repo', 'view', '--json', 'nameWithOwner', '--jq', '.nameWithOwner']).trim()}`)
    existing = new Map(
      JSON.parse(sh('gh', ['label', 'list', '--limit', '200', '--json', 'name,color,description']))
        .map((l) => [l.name, l]),
    )
  } catch {
    console.error('error: --remote needs GitHub, and it could not be reached')
    process.exit(1)
  }

  // A declared label whose older synonym is still on GitHub is a rename, not a
  // creation. Renaming keeps the label and everything filed under it.
  const renames = declared.filter((l) => l.supersedes && !existing.has(l.name) && existing.has(l.supersedes))
  const renaming = new Set(renames.map((l) => l.name))
  const missing = declared.filter((l) => !existing.has(l.name) && !renaming.has(l.name))
  const wrong = declared.filter((l) => {
    const cur = existing.get(l.name)
    return cur && (norm(cur.color) !== norm(l.color) || (cur.description ?? '') !== (l.description ?? ''))
  })
  const superseded = new Set(renames.map((l) => l.supersedes))
  const retire = retiring.filter((l) => existing.has(l.name))
  const retiringNames = new Set(retire.map((l) => l.name))
  const unmanaged = [...existing.keys()].filter(
    (n) => !declared.some((l) => l.name === n) && !superseded.has(n) && !retiringNames.has(n),
  )

  if (apply) {
    for (const l of renames) {
      sh('gh', ['label', 'edit', l.supersedes, '--name', l.name, '--color', norm(l.color),
                '--description', l.description ?? ''])
      console.log(`renamed ${l.supersedes} -> ${l.name}`)
    }
    for (const l of missing) {
      sh('gh', ['label', 'create', l.name, '--color', norm(l.color), '--description', l.description ?? ''])
      console.log(`created ${l.name}`)
    }
    for (const l of wrong) {
      sh('gh', ['label', 'edit', l.name, '--color', norm(l.color), '--description', l.description ?? ''])
      console.log(`updated ${l.name}`)
    }
    for (const l of retire) {
      sh('gh', ['label', 'delete', l.name, '--yes'])
      console.log(`deleted ${l.name}`)
    }
  } else {
    for (const l of renames) console.log(`would rename ${l.supersedes} -> ${l.name}`)
    for (const l of missing) console.log(`would create ${l.name}`)
    for (const l of wrong) console.log(`would update ${l.name}`)
    for (const l of retire) console.log(`would delete ${l.name} -- ${l.description ?? 'retired'}`)
  }

  if (unmanaged.length) {
    console.log(`\n${unmanaged.length} label(s) on GitHub that labels.yml does not describe, left alone:`)
    console.log(`  ${unmanaged.join(', ')}`)
  }

  console.log(
    `\n${declared.length} declared, ${renames.length} to rename, ${missing.length} to create, ` +
      `${wrong.length} to correct, ${retire.length} to delete, ${unmanaged.length} unmanaged.`,
  )

  // Colour drift is fixable by re-running with --apply, so it is not worth
  // failing over. An undeclared tag is not: the vocabulary and the graph
  // disagree, and only a person can say which one is right.
  if (problems.length) process.exit(1)
}

// Importable for tests: running the module must not fire a gh call.
if (process.argv[1] === fileURLToPath(import.meta.url)) main()
